files:
  - source: /iina/mul.lproj/*.xcstrings
    translation: /iina/mul.lproj/%original_file_name%
    multilingual: 1
  - source: /iina/*.xcstrings
    translation: /iina/%original_file_name%
    multilingual: 1
